package com.caritasdesigns.testpits;

public enum Mode {

	PROJECT_CREATE_MODE, PROJECT_UPDATE_MODE, PROJECT_READ_MODE,
	TESTPIT_CREATE_MODE, TESTPIT_UPDATE_MODE, TESTPIT_READ_MODE,
	HORIZON_CREATE_MODE, HORIZON_UPDATE_MODE, HORIZON_READ_MODE
}
